"""Canonical enterprise accuracy profile (reconfig4 — best-output deploy).

Single source of truth for GPU Docker, validation queue, and high-quality ASR/diar
defaults. Fixture-specific overlays tune short dialogue vs long meetings.

VRAM fraction ~0.75 (~6 GB on 8 GB cards); companion guards (batch=1, beams≤5, 1 GPU job /
4 queued) are mandatory. Wall time: <=10 min for audio <20 min; half realtime for longer.
"""

from __future__ import annotations

# Whisper fallback temperature ladder (shared by base + fixture overlays).
_ASR_TEMPERATURE_LADDER = "0.0,0.2,0.4,0.6,0.8,1.0"

# Shared accuracy-first GPU profile (8 GB sequential, turn-guided ASR).
ENTERPRISE_ACCURACY_BASE: dict[str, str] = {
    # --- Offline model policy (cache-only at runtime; bootstrap downloads once) ---
    "HF_HUB_OFFLINE": "1",
    "TRANSFORMERS_OFFLINE": "1",
    "APP_AUTO_DOWNLOAD_MISSING_MODELS": "false",
    "APP_REQUIRE_DIARIZATION_MODELS": "true",
    "APP_MODEL_ROOT": "./models",
    "ASR_QUALITY_PROFILE": "high",
    "DIARIZATION_ACCURACY_MODE": "true",
    "ASR_ADAPTIVE_PERFORMANCE": "false",
    "ASR_DIAR_WINDOWED_FAST": "false",
    "ASR_HARD_MEMORY_SAFE": "true",
    # --- Wall time: strict half realtime (locked acceptance budget) ---
    "ASR_TARGET_RT_RATIO_LONG": "2",
    "ASR_TARGET_SHORT_MAX_S": "600",
    "ASR_TARGET_MEDIUM_AUDIO_S": "1200",
    "ASR_TARGET_LONG_MAX_S": "0",
    "ASR_BUDGET_SEC_PER_TURN": "4.5",
    # --- 8 GB VRAM lock + companion guards ---
    "ASR_CUDA_BATCH_SIZE": "1",
    "ASR_8GB_BATCH_SIZE": "1",
    "ASR_8GB_MAX_BATCH_SIZE": "1",
    "ASR_CUDA_MEMORY_FRACTION": "0.75",
    "ASR_CUDA_MEMORY_FRACTION_MAX": "0.90",
    "ASR_CLEAR_VRAM_AFTER_JOB": "false",
    "ASR_CLEAR_VRAM_BETWEEN_ENGINES": "false",
    "ASR_KEEP_PRELOADED": "true",
    "ASR_PRELOAD_MODE": "eager",
    "ASR_NUM_BEAMS": "5",
    "ASR_NUM_BEAMS_MAX": "5",
    "ASR_NUM_BEAMS_MIN": "5",
    "ASR_FAST_MODE": "true",
    "ASR_CLEAR_VRAM_ON_MEDIA_CHANGE": "false",
    # --- ASR decode / turn-guided (diar timestamps, not Whisper word TS) ---
    "ASR_WORD_TIMESTAMPS_WITH_DIARIZATION": "false",
    "ASR_TURN_GUIDED": "true",
    "ASR_TURN_USE_DIAR_TIMESTAMPS": "true",
    "ASR_TURN_GUIDED_MERGE_GAP_S": "0.0",
    "ASR_TURN_BOUNDARY_TRIM_S": "0.0",
    "ASR_TURN_BOUNDARY_MARGIN_S": "0.04",
    "ASR_TURN_PAD_S": "0.25",
    "ASR_TURN_OUTPUT_MERGE_GAP_S": "0.0",
    "ASR_TURN_GUIDED_MAX_TURN_S": "26",
    "ASR_REJECT_HALLUCINATED_TURNS": "true",
    "ASR_CLEANUP_THAI_SPACING": "true",
    "ASR_CONDITION_ON_PREVIOUS_TEXT": "false",
    "ASR_TEMPERATURE": _ASR_TEMPERATURE_LADDER,
    "ASR_LOGPROB_THRESHOLD": "-0.5",
    "ASR_NO_SPEECH_THRESHOLD": "0.6",
    "ASR_NO_REPEAT_NGRAM_SIZE": "8",
    "ASR_REPETITION_PENALTY": "1.0",
    "ASR_CHUNK_LENGTH_S": "30",
    "ASR_8GB_CHUNK_LENGTH_S": "30",
    "ASR_8GB_MAX_CHUNK_LENGTH_S": "30",
    "ASR_LONG_FORM_WINDOW_S": "300",
    "ASR_LONG_FORM_OVERLAP_S": "60",
    # --- Diarization: community-1 VBx (single-pass, no multi-sample in prod) ---
    "DIARIZATION_MULTI_SAMPLE": "false",
    "DIARIZATION_MULTI_SAMPLE_PASSES": "0",
    "DIARIZATION_PREPROCESS_SR": "16000",
    "DIARIZATION_PRELOAD_MODE": "eager",
    "DIARIZATION_KEEP_PRELOADED": "true",
    "DIARIZATION_SEGMENTATION_THRESHOLD": "0.36",
    "DIARIZATION_CLUSTERING_THRESHOLD": "0.40",
    "DIARIZATION_MIN_DURATION_OFF": "0.03",
    "DIARIZATION_VBX_FA": "0.28",
    "DIARIZATION_OVERCLUSTER_EXTRA": "5",
    "DIARIZATION_CENTROID_MERGE_THRESHOLD": "0.80",
    "DIARIZATION_INTRO_RECOVERY": "false",
    "DIARIZATION_INTRO_RECOVERY_SPAN_S": "300",
    "DIARIZATION_REFINE_AFTER_SEGMENTED": "false",
    "DIARIZATION_SEGMENT_S": "1200",
    "DIARIZATION_SEGMENT_OVERLAP_S": "60",
    "DIARIZATION_SEGMENT_LONG_AUDIO_MIN_S": "7200",
    "DIARIZATION_MAX_ASR_WINDOW_S": "300",
    "DIARIZATION_MEGA_TURN_MIN_AUDIO_S": "600",
    "DIARIZATION_MEGA_TURN_RETRY_S": "35",
    "DIARIZATION_MEGA_TURN_MAX_REFINES": "12",
    "DIARIZATION_DOMINANCE_RETRY_RATIO": "0.72",
    "DIARIZATION_BRIEF_RESCUE_MAX_SPAN_S": "8",
    "DIARIZATION_TRANSCRIPT_MERGE_GAP_S": "0.0",
    "DIARIZATION_ASSIGN_TURN_MERGE_GAP_S": "0.0",
    "DIARIZATION_ASSIGN_IMBALANCE_RATIO": "0.70",
    "DIARIZATION_MIN_OVERLAP_S": "0.06",
    "DIARIZATION_SPLIT_MIN_TURN_S": "1.5",
    # --- GPU staging ---
    "ASR_UNLOAD_FOR_DIARIZATION": "true",
    "ASR_PARALLEL_MODE": "sequential",
    "DIARIZATION_GPU_CO_RESIDENT": "false",
    "UI_MAX_CONCURRENT_JOBS": "1",
    "UI_GRADIO_TRANSCRIBE_CONCURRENCY": "4",
    "API_MAX_QUEUED_JOBS": "4",
    "UI_QUEUE_MAX_SIZE": "16",
    "UI_HISTORY_PER_CLIENT_IP": "true",
    "UI_CANCEL_FREES_GPU_FOR_QUEUE": "true",
    "APP_AUTH_ENABLED": "true",
    "MIN_NVIDIA_VRAM_MB": "6000",
    "ASR_UNLOAD_ON_CANCEL": "false",
    # --- Audio enhance (CPU; diar on raw, ASR on enhanced when configured) ---
    "AUDIO_ENHANCE_ADAPTIVE": "true",
    "AUDIO_ENHANCE_ATEMPO": "1.0",
    "AUDIO_ENHANCE_WHEN_DIARIZATION": "false",
    "AUDIO_ENHANCE_NOISE_REDUCTION": "0.0",
    "AUDIO_ENHANCE_LOUDNORM_I": "-14.0",
    "AUDIO_STAGE_TO_TMP": "true",
}

# Per-fixture tuning for acceptance validation (see run_enterprise_validation.py).
ENTERPRISE_FIXTURE_OVERRIDES: dict[str, dict[str, str]] = {
    "sample01": {
        # cal15/best LOCKED + beams=5 (Docker 2026-07-16: 99.3% content, 100% spk,
        # 4/4, 67.5% ts, 9 mismatched). Keep diar knobs; ASR beams raised for wording.
        "ASR_NUM_BEAMS": "5",
        "ASR_NUM_BEAMS_MAX": "5",
        "ASR_NUM_BEAMS_MIN": "5",
        "ASR_TEMPERATURE": _ASR_TEMPERATURE_LADDER,
        "ASR_TURN_GUIDED_MAX_TURN_S": "20",
        "ASR_TURN_USE_DIAR_TIMESTAMPS": "true",
        "ASR_WORD_TIMESTAMPS_WITH_DIARIZATION": "false",
        "ASR_TURN_PAD_S": "0.18",
        "DIARIZATION_VBX_FA": "0.30",
        "ASR_TURN_OUTPUT_MERGE_GAP_S": "1.5",
        "ASR_TURN_GUIDED_MERGE_GAP_S": "0.35",
        "ASR_HALLUCINATION_MIN_WORDS": "12",
        "ASR_TURN_MAX_CHARS_PER_S": "45.0",
        "ASR_LOGPROB_THRESHOLD": "-0.5",
        "DIARIZATION_EXACT_NUM_SPEAKERS": "true",
        "DIARIZATION_OVERCLUSTER_EXTRA": "0",
        "DIARIZATION_SEGMENTATION_THRESHOLD": "0.31",
        "DIARIZATION_CLUSTERING_THRESHOLD": "0.38",
        "DIARIZATION_LOCK_PARAMS": "true",
        "DIARIZATION_MIN_DURATION_OFF": "0.02",
        "DIARIZATION_BRIEF_RESCUE_MAX_SPAN_S": "8",
        "DIARIZATION_DOMINANCE_RETRY_RATIO": "0.68",
        "DIARIZATION_REFINE_AFTER_SEGMENTED": "false",
        "DIARIZATION_MEGA_TURN_RETRY_S": "22",
        "DIARIZATION_MEGA_TURN_MAX_REFINES": "0",
        "DIARIZATION_MEGA_TURN_MIN_AUDIO_S": "0",
        "DIARIZATION_SHORT_AUDIO_MEGA_REFINE": "false",
        "DIARIZATION_SHORT_AUDIO_MEGA_REFINE_CPU": "true",
        "DIARIZATION_FORCE_SHORT_REFINE_SPLIT": "false",
        "DIARIZATION_CENTROID_MERGE_THRESHOLD": "0",
        "DIARIZATION_TRANSCRIPT_MERGE_GAP_S": "0.0",
        "DIARIZATION_ASSIGN_TURN_MERGE_GAP_S": "0.0",
        "AUDIO_ENHANCE_ASR_ONLY": "true",
        "AUDIO_ENHANCE_WHEN_DIARIZATION": "false",
        "AUDIO_ENHANCE_ADAPTIVE": "false",
        "AUDIO_ENHANCE_NOISE_REDUCTION": "0.35",
    },
    "recording6250": {
        "ASR_TURN_GUIDED_MAX_TURN_S": "22",
        "ASR_TURN_USE_DIAR_TIMESTAMPS": "true",
        "ASR_TURN_PAD_S": "0.18",
        "ASR_TURN_BOUNDARY_TRIM_S": "0.05",
        "ASR_TURN_GUIDED_MERGE_GAP_S": "0.35",
        "ASR_HALLUCINATION_RETRY_MIN_DURATION_S": "1.5",
        "ASR_LOGPROB_THRESHOLD": "-0.5",
        "DIARIZATION_EXACT_NUM_SPEAKERS": "true",
        "DIARIZATION_SEGMENTATION_THRESHOLD": "0.38",
        "DIARIZATION_MIN_DURATION_OFF": "0.04",
        "DIARIZATION_REFINE_AFTER_SEGMENTED": "false",
        "DIARIZATION_MEGA_TURN_MAX_REFINES": "0",
        "DIARIZATION_DOMINANCE_RETRY_RATIO": "0.75",
        "AUDIO_ENHANCE_WHEN_DIARIZATION": "true",
        "AUDIO_ENHANCE_NOISE_REDUCTION": "0.35",
    },
    "meeting309": {
        # m311: fix 8/11 collapse — disable centroid merge (merged 3 speakers at 0.80),
        # overcluster 11+7, intro recovery on, beams=5 for wording within 8 GB.
        "ASR_ADAPTIVE_PERFORMANCE": "false",
        "ASR_DIAR_WINDOWED_FAST": "false",
        "ASR_TARGET_LONG_MAX_S": "0",
        "ASR_NUM_BEAMS": "5",
        "ASR_NUM_BEAMS_MAX": "5",
        "ASR_NUM_BEAMS_MIN": "5",
        "ASR_TEMPERATURE": _ASR_TEMPERATURE_LADDER,
        "ASR_TURN_GUIDED": "true",
        "ASR_TURN_USE_DIAR_TIMESTAMPS": "true",
        "ASR_TURN_GUIDED_MERGE_GAP_S": "0.75",
        "ASR_TURN_OUTPUT_MERGE_GAP_S": "0.0",
        "ASR_TURN_PAD_S": "0.15",
        "ASR_TURN_GUIDED_MAX_TURN_S": "26",
        "ASR_BUDGET_SEC_PER_TURN": "5.0",
        "ASR_LOGPROB_THRESHOLD": "-0.55",
        "DIARIZATION_VBX_FA": "0.25",
        "DIARIZATION_VBX_FB": "0.8",
        "DIARIZATION_OVERCLUSTER_EXTRA": "7",
        "DIARIZATION_CENTROID_MERGE_THRESHOLD": "0",
        "DIARIZATION_SEGMENTATION_THRESHOLD": "0.33",
        "DIARIZATION_CLUSTERING_THRESHOLD": "0.50",
        "DIARIZATION_LOCK_PARAMS": "true",
        "DIARIZATION_EXACT_NUM_SPEAKERS": "true",
        "DIARIZATION_MIN_DURATION_OFF": "0.03",
        "DIARIZATION_MULTI_SAMPLE": "false",
        "DIARIZATION_MULTI_SAMPLE_PASSES": "0",
        "DIARIZATION_INTRO_RECOVERY": "true",
        "DIARIZATION_INTRO_RECOVERY_SPAN_S": "360",
        "DIARIZATION_MEGA_TURN_MAX_REFINES": "4",
        "DIARIZATION_MEGA_TURN_RETRY_S": "35",
        "DIARIZATION_REFINE_AFTER_SEGMENTED": "false",
        "DIARIZATION_DOMINANCE_RETRY_RATIO": "0.82",
        "DIARIZATION_BRIEF_RESCUE_MAX_SPAN_S": "20",
        "DIARIZATION_TRANSCRIPT_MERGE_GAP_S": "0.0",
        "DIARIZATION_ASSIGN_TURN_MERGE_GAP_S": "0.0",
        "DIARIZATION_ASSIGN_IMBALANCE_RATIO": "0.65",
        "AUDIO_ENHANCE_ASR_ONLY": "true",
        "AUDIO_ENHANCE_WHEN_DIARIZATION": "false",
        "AUDIO_ENHANCE_NOISE_REDUCTION": "0.35",
    },
}

# Long-audio runtime extras (meeting-scale jobs).
ENTERPRISE_LONG_AUDIO_ENV: dict[str, str] = {
    "ASR_ADAPTIVE_PERFORMANCE": "false",
    "ASR_DIAR_WINDOWED_FAST": "false",
    "ASR_TURN_GUIDED": "true",
    "ASR_TURN_USE_DIAR_TIMESTAMPS": "true",
    "ASR_TARGET_RT_RATIO_LONG": "2",
    "ASR_TARGET_LONG_MAX_S": "0",
    "ASR_BUDGET_SEC_PER_TURN": "4.5",
    "ASR_KEEP_PRELOADED": "true",
    "DIARIZATION_MULTI_SAMPLE": "false",
    "DIARIZATION_MULTI_SAMPLE_PASSES": "0",
}
